version: '3'
services:
  proxy-service:
    build: ./proxyserver
    volumes:
      - ./proxyserver:/usr/src/app
    ports:
      - 8080:8080
    environment:
      - PYTHONUNBUFFERED=0
  application-service:
    build: ./applicationserver
    volumes:
      - ./applicationserver:/usr/src/app
    ports:
      - 9090:9090
    environment:
      - PYTHONUNBUFFERED=0
